#Builder configuration

#The directory to look for schematics. 
SchematicsFolder: plugins/Builder/schematics/

#The allowed materials for plot marking, the first one in the list is the default. 
#Use Id or Name. Should only use base blocks, not things that can break on place (like TORCH).
MarkMaterials: 
 - GLASS
 - GLOWSTONE
 - BEDROCK
  
#Customize the messages Builder sends. <NPC> and <SCHEMATIC> can be used as placeholders.
DefaultTexts:
 BuildStarted: <NPC> has started to build <SCHEMATIC>!
 BuildComplete: <NPC> has completed build of <SCHEMATIC>!
 BuildCanceled: <NPC>'s build of <SCHEMATIC> has been canceled!
 Mark: <NPC> is marking the corners of <SCHEMATIC>
 
