defaults:
  lucky hits:
    enabled: true
    maim_message: '*** You MAIM the sentry!'
    maim_damage_modifier: 2.5
    dismember_message: '*** You DISMEMBER the sentry!'
    dismember_damage_modifier: 2.0
    injure_message: '*** You INJURE the sentry!'
    injure_damage_modifier: 1.5
    miss_message: '*** You MISS the sentry!'
    miss_damage_modifier: 0.0
    mortal_blow_message: '*** You lay a mortal blow to the sentry!'
  speed: .2
  health: 20
  
  