name: Builder
author: jrbudda
version: 0.1
main: net.jrbudda.builder.Builder
depend:
  - Citizens
commands:
  builder:
    description: Lists builder commands.
    usage: /builder help
permissions:
  builder.*:
    default: op
    children:
      builder.load: true
      builder.cancel: true
      builder.build.*: true
